// src/app/member/diet/[planId]/page.tsx
"use client"

import { useEffect, useState, useCallback } from "react"
import { useParams, useRouter } from "next/navigation"
import { ArrowLeft, UtensilsCrossed, Flame, Sparkles } from "lucide-react"
import { AIPlanEditPanel } from "@/components/member/AIPlanEditPanel"
const DAYS = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

function todayName() {
  return DAYS[new Date().getDay() === 0 ? 6 : new Date().getDay() - 1]
}

function getSlotsForDay(planData: Record<string, any[]>, day: string) {
  const prefix = `${day}__`
  return Object.keys(planData)
    .filter(k => k.startsWith(prefix))
    .map(k => k.slice(prefix.length))
    .sort((a, b) => {
      // Sort by scheduledTime (HH:MM 24h) from the first item in each slot
      const ta = planData[`${day}__${a}`]?.[0]?.scheduledTime ?? "99:99"
      const tb = planData[`${day}__${b}`]?.[0]?.scheduledTime ?? "99:99"
      return ta.localeCompare(tb)
    })
}

export default function MemberDietDetailPage() {
  const { planId } = useParams<{ planId: string }>()
  const router     = useRouter()

  const [plan, setPlan]           = useState<any>(null)
  const [loading, setLoading]     = useState(true)
  const [activeDay, setActiveDay] = useState(todayName())

  const loadPlan = useCallback(() => {
    setLoading(true)
    fetch(`/api/member/diet/${planId}`)
      .then(r => r.ok ? r.json() : Promise.reject())
      .then(setPlan)
      .catch(() => router.replace("/member/diet"))
      .finally(() => setLoading(false))
  }, [planId, router])

    useEffect(() => { loadPlan() }, [loadPlan])
  if (loading) return (
    <div className="max-w-3xl space-y-5 animate-pulse">
      <div className="h-8 w-56 bg-white/5 rounded" />
      <div className="h-28 bg-white/5 rounded-2xl" />
      <div className="h-12 bg-white/5 rounded-xl" />
      <div className="h-64 bg-white/5 rounded-2xl" />
    </div>
  )
  if (!plan) return null

  const planData: Record<string, any[]> = plan.planData ?? {}
  const slots   = getSlotsForDay(planData, activeDay)
  const allItems = slots.flatMap(s => planData[`${activeDay}__${s}`] ?? [])
  const totals   = allItems.reduce(
    (acc, item) => ({
      calories: acc.calories + (Number(item.calories)                   || 0),
      protein:  acc.protein  + (Number(item.protein_g ?? item.protein)  || 0),
      carbs:    acc.carbs    + (Number(item.carbs_g   ?? item.carbs)    || 0),
      fat:      acc.fat      + (Number(item.fat_g     ?? item.fat)      || 0),
    }),
    { calories: 0, protein: 0, carbs: 0, fat: 0 }
  )

  return (
    <div className="max-w-3xl space-y-5">
      <button onClick={() => router.back()}
        className="flex items-center gap-2 text-white/50 hover:text-white transition-colors text-sm">
        <ArrowLeft className="w-4 h-4" /> Back to Diet Plans
      </button>

      {/* Header card */}
      <div className="bg-[hsl(220_25%_9%)] border border-white/6 rounded-2xl p-6">
        <div className="flex items-start justify-between gap-3 flex-wrap">
          <div className="flex-1 min-w-0">
            <h2 className="text-white font-bold text-xl">{plan.title}</h2>
            {plan.goal && <p className="text-primary/70 text-sm mt-1">🎯 {plan.goal}</p>}
          </div>
          {plan.caloriesTarget && (
            <span className="flex items-center gap-1 text-orange-400 bg-orange-500/10 border border-orange-500/15 px-3 py-1.5 rounded-full text-sm font-semibold shrink-0">
              <Flame className="w-3.5 h-3.5" /> {plan.caloriesTarget} kcal/day
            </span>
          )}
        </div>
        {(plan.proteinG || plan.carbsG || plan.fatG) && (
          <div className="flex gap-2 mt-3 flex-wrap">
            {plan.proteinG && <span className="text-xs bg-blue-500/10 text-blue-400 px-3 py-1.5 rounded-lg">Protein {plan.proteinG}g</span>}
            {plan.carbsG   && <span className="text-xs bg-yellow-500/10 text-yellow-400 px-3 py-1.5 rounded-lg">Carbs {plan.carbsG}g</span>}
            {plan.fatG     && <span className="text-xs bg-red-500/10 text-red-400 px-3 py-1.5 rounded-lg">Fat {plan.fatG}g</span>}
          </div>
        )}
        <div className="flex items-center gap-2 mt-4 flex-wrap">
          <p className="text-white/35 text-xs">
            {plan.isAIGenerated ? "Generated by AI" : `Assigned by ${plan.creator?.fullName ?? "your trainer"}`} · {plan.gym?.name}
          </p>
          {plan.isAIGenerated && (
            <span className="flex items-center gap-1 text-[10px] font-semibold bg-primary/10 text-primary border border-primary/20 px-2 py-0.5 rounded-full">
              <Sparkles className="w-2.5 h-2.5" /> AI Generated
            </span>
          )}
        </div>
      </div>

      {/* Day tabs */}
      <div className="flex gap-1 bg-white/4 rounded-xl p-1 overflow-x-auto">
        {DAYS.map(day => {
          const daySlots = getSlotsForDay(planData, day)
          const hasData  = daySlots.some(s => (planData[`${day}__${s}`]?.length ?? 0) > 0)
          const isToday  = day === todayName()
          return (
            <button key={day} onClick={() => setActiveDay(day)}
              className={`flex-1 py-2 rounded-lg text-xs font-medium whitespace-nowrap transition-all relative min-w-12 ${
                activeDay === day ? "bg-[hsl(220_25%_13%)] text-white shadow" : "text-white/40 hover:text-white/70"
              }`}>
              {day.slice(0, 3)}
              {isToday && <span className="absolute top-0.5 right-0.5 w-1 h-1 bg-primary rounded-full" />}
              {hasData && activeDay !== day && (
                <span className="absolute bottom-0.5 left-1/2 -translate-x-1/2 w-1 h-1 bg-white/25 rounded-full" />
              )}
            </button>
          )
        })}
      </div>

      {/* Daily macro summary */}
      {slots.length > 0 && (
        <div className="grid grid-cols-4 gap-2">
          {[
            { label: "kcal",    value: totals.calories, color: "bg-orange-500/8 border-orange-500/15 text-orange-400" },
            { label: "protein", value: `${totals.protein}g`, color: "bg-blue-500/8 border-blue-500/15 text-blue-400" },
            { label: "carbs",   value: `${totals.carbs}g`,   color: "bg-yellow-500/8 border-yellow-500/15 text-yellow-400" },
            { label: "fat",     value: `${totals.fat}g`,     color: "bg-red-500/8 border-red-500/15 text-red-400" },
          ].map(({ label, value, color }) => (
            <div key={label} className={`border rounded-xl p-3 text-center ${color}`}>
              <p className="font-bold text-sm">{value}</p>
              <p className="text-[10px] opacity-60 mt-0.5">{label}</p>
            </div>
          ))}
        </div>
      )}

      {/* Meal slots */}
      <div className="bg-[hsl(220_25%_9%)] border border-white/6 rounded-2xl overflow-hidden">
        <div className="px-5 py-4 border-b border-white/5 flex items-center gap-2">
          <UtensilsCrossed className="w-4 h-4 text-primary" />
          <h3 className="text-white font-semibold text-sm">
            {activeDay}{activeDay === todayName() ? " (Today)" : ""}
          </h3>
          <span className="ml-auto text-white/30 text-xs">{slots.length} meal{slots.length !== 1 ? "s" : ""}</span>
        </div>

        {slots.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-14 gap-2">
            <UtensilsCrossed className="w-8 h-8 text-white/10" />
            <p className="text-white/25 text-sm">No meals planned for {activeDay}</p>
          </div>
        ) : (
          <div className="divide-y divide-white/4">
            {slots.map(slot => {
              const items = planData[`${activeDay}__${slot}`] ?? []
              // AI-generated plans have one meal object per slot with a foods[] array
              const isAIFormat = items.some((item: any) => Array.isArray(item.foods))

              return (
                <div key={slot} className="p-5">
                  <div className="flex items-center gap-3 mb-3">
                    <span className="text-xs font-mono bg-primary/15 text-primary px-2.5 py-1 rounded-lg font-semibold">{slot}</span>
                    {isAIFormat && items[0]?.scheduledTime && (
                      <span className="text-white/30 text-xs">{items[0].scheduledTime}</span>
                    )}
                    {!isAIFormat && (
                      <span className="text-white/30 text-xs">{items.length} item{items.length !== 1 ? "s" : ""}</span>
                    )}
                  </div>
                  <div className="space-y-2">
                    {isAIFormat ? (
                      items.map((item: any, idx: number) => (
                        <div key={idx}>
                          {(item.protein_g || item.carbs_g || item.fat_g || item.calories) && (
                            <div className="flex items-center gap-3 mb-2.5 flex-wrap">
                              {item.calories  && <span className="text-orange-400/80 text-xs bg-orange-500/8 px-2 py-0.5 rounded-full">{item.calories} kcal</span>}
                              {item.protein_g && <span className="text-blue-400/70 text-xs">P:{item.protein_g}g</span>}
                              {item.carbs_g   && <span className="text-yellow-400/70 text-xs">C:{item.carbs_g}g</span>}
                              {item.fat_g     && <span className="text-red-400/70 text-xs">F:{item.fat_g}g</span>}
                            </div>
                          )}
                          {Array.isArray(item.foods) && item.foods.map((food: string, fi: number) => (
                            <div key={fi} className="flex items-center gap-2.5 p-2.5 bg-white/3 rounded-lg mb-1.5 last:mb-0">
                              <span className="w-1.5 h-1.5 bg-primary/50 rounded-full shrink-0" />
                              <p className="text-white/80 text-sm">{food}</p>
                            </div>
                          ))}
                        </div>
                      ))
                    ) : (
                      items.map((item: any, idx: number) => (
                        <div key={idx} className="flex items-center gap-3 p-3 bg-white/3 rounded-xl">
                          <div className="flex-1 min-w-0">
                            <p className="text-white text-sm font-medium truncate">{item.name}</p>
                            {item.quantity && <p className="text-white/35 text-xs mt-0.5">{item.quantity}</p>}
                          </div>
                          <div className="flex items-center gap-2 shrink-0 flex-wrap justify-end">
                            {item.calories && <span className="text-orange-400/80 text-xs bg-orange-500/8 px-2 py-0.5 rounded-full">{item.calories} kcal</span>}
                            {item.protein  && <span className="text-blue-400/70 text-xs">P:{item.protein}g</span>}
                            {item.carbs    && <span className="text-yellow-400/70 text-xs">C:{item.carbs}g</span>}
                            {item.fat      && <span className="text-red-400/70 text-xs">F:{item.fat}g</span>}
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </div>

      {plan.isAIGenerated && <AIPlanEditPanel planId={planId} onUpdate={loadPlan} />}
    </div>
  )
}
